# Generated by Django 5.1.1 on 2024-09-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Member',
        ),
    ]
